# cloudbuild.yaml
steps:
  # build & push the container image
- name: "gcr.io/kaniko-project/executor:latest"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/bright-calculus-256912/s_p_stream:latest"]
  # Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'spstream', '--image', 'gcr.io/bright-calculus-256912/s_p_stream:latest', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']